name: swipe_core_cards
description: Tinder like swipe cards.
version: 2.0.1
homepage: https://github.com/cyberprophet/swipe_cards

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
